apiVersion: v1
kind: Service
metadata:
  name: worker
  labels:
    app: guestbook
    tier: worker
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: guestbook
    tier: worker
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: guestbook
        tier: worker
    spec:
      containers:
      - name: worker
        image: nrlabs/newrelic-k8s-guestbook-worker:latest
        imagePullPolicy: Never
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
        env:
        - name: NEW_RELIC_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: guestbook-secret
              key: new_relic_license_key
        - name: NEW_RELIC_APP_NAME
          value: New Relic Guestbook k8s - Worker
        - name: GET_HOSTS_FROM
          value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below:
          # value: env
        #
        # The following information comes from the Downward API:
        # Docs: https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/
        # Tutorial: https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/
        # Listing: https://kubernetes.io/docs/resources-reference/v1.7/#envvarsource-v1-core
        - name: K8S_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name    
        ports:
          - containerPort: 3000